---
name: Transform Pouch CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: couchdb
    strategy:
      matrix:
        node: [12, 14, 16]
        command: [test, coverage]
    steps:
      - uses: actions/checkout@v2

      - name: build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - run: |
          npm run ${{ matrix.command }}
