---
name: Transform Pouch CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: couchdb
    strategy:
      matrix:
        node: [12, 14, 16]
        command: [test, coverage]
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm run ${{ matrix.command }}
